name: Sync and Modify Ruleset
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点自动同步
  workflow_dispatch:      # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          # 移除 path 参数
          fetch-depth: 0  # 获取完整历史记录


      - name: Clone source ruleset
        run: |
          git clone --depth 1 --filter=blob:none \
            --branch mihomo-ruleset \
            https://github.com/DustinWin/ruleset_geodata.git \
            source-repo

      - name: Debug directory structure
        run: |
          ls -la
          ls -la .github
          ls -la .github/scripts

      - name: Modify .list files
        run: |
          python ${{ github.workspace }}/.github/scripts/modify_rules.py

      - name: Commit & Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto: Update ruleset"
          git push origin HEAD:refs/for/ruleset

      - name: Clean up
        run: rm -rf source-repo
